variables:
    PLUGIN_NAME: 'dataverse'
    SAST_EXCLUDED_PATHS: libs/swordappv2-php-library
    
include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: motivosConflitoTemplates#324
    file:
      - 'templates/groups/pkp_plugin.yml'
